F#EXTM3U
#EXTINF:-0, ||||||| sports |||||||
http://www.elahmad.com/tv/m3u8/2ktv.m3u8?id=ktv3
#EXTINF:0, Alfajertv tv
http://two.alfajertv.com:8081/AlfajertvHDTwo_web/web/chunks.m3u8
#EXTINF:0, Raya TV 
http://htvmada.mada.ps:8888/raya/playlist.m3u8
#EXTINF:-0,ajeyel tv hd 
http://htvajyal.mada.ps:8888/ajyal/playlist.m3u8
#EXTINF:-0, HR tv
http://vstream3.hadara.ps:8081/hrHD_web/web/chunks.m3u8
#EXTINF:-0, ||||||| qurren |||||||
http://www.elahmad.com/tv/m3u8/ktv.m3u8?id=ktv3
#EXTINF:-1,quran
http://cdnamd-hls-globecast.akamaized.net/live/ramdisk/saudi_quran/hls1/saudi_quran-avc1_600000=4-mp4a_97200=2.m3u8
#EXTINF:-1,quran +
http://m.live.net.sa:1935/live/quran/chunklist.m3u8
#EXTINF:-1,sunnah 
http://cdnamd-hls-globecast.akamaized.net/live/ramdisk/saudi_sunnah/hls1/saudi_sunnah-avc1_600000=4-mp4a_97200=2.m3u8
#EXTINF:-1,sunnah +
http://livecdnh2.tvanywhere.ae/hls/sunnah/02.m3u8
#EXTINF:0,Bahrain Quran
http://185.105.4.106:1935/live/Bahrain%20Quran/chunklist.m3u8
#EXTINF:0,alistiqama
http://jmc-live.ercdn.net/alistiqama/alistiqama_576p.m3u8
#EXTINF:0,makka
http://makkahtv.srfms.com:1935/makkahtv/livestream/chunklist_w47862988.m3u8
#EXTINF:-0,Wesal tv
http://live.noorlive.com:1935/wesal/wesal1/chunklist_w1680220937.m3u8
#EXTINF:-0,resalah
http://livecdnh3.tvanywhere.ae/hls/resalah/03.m3u8
#EXTINF:-0,iqraa
http://iqraac.cdn.mangomolo.com/iqraa/smil:iqraar1.stream.smil/chunklist.m3u8
#EXTINF:-0,eyakanabod
http://livecdnh3.tvanywhere.ae/hls/majd/03.m3u8 
#EXTINF:-0, ||||||| kids|||||||
http://www.elahmad.com/tv/m3u8/22ktv.m3u8?id=ktv3
#EXTINF:-0,TOYOR-BABY 
http://130.185.144.164/toyor.php
#EXTINF:-0,spacetoon
http://livecdnh2.tvanywhere.ae/hls/spacetoon/04.m3u8
#EXTINF:-0,spacetoon +
https://streams.spacetoon.com/live/stchannel/smil:livesmil.smil/chunklist_w77869824_b1296000_slAR.m3u8
#EXTINF:0,karameesh
http://188.160.0.148:1935/5c33373f8c73484/definst/smil:myStream.smil/playlist.m3u8
#EXTINF:0,Majid Kids
https://admdn4.cdn.mangomolo.com/majid/smil:majid.stream.smil/chunklist.m3u8
#EXTINF:0,rotana kids
https://rotana.hibridmedia.com/rotana/kids_dabr/rotana/kids_1080p/chunks.m3u8
#EXTINF:-0, ||||||| news   |||||||
http://static.france24.com/live/F24_AR_LO_HLS/live_web.m3u8
#EXTINF:-0,ALJAZEERA 
https://live-hls-web-aja.getaj.net/AJA/01.m3u8
#EXTINF:-0,alhiwar
http://mn-nl.mncdn.com/alhiwar_live/smil:alhiwar.smil/chunklist.m3u8
#EXTINF: -1,Mekameleen 
https://mn-nl.mncdn.com/mekameleen/smil:mekameleentv.smil/chunklist.m3u8
#EXTINF: -1,Al Mayadeen
http://mdnlv.cdn.octivid.com/almdn/smil:mpegts.stream.smil/chunklist.m3u8
#EXTINF:-0,Al Manar
http://manar.live/x.smil/index.m3u8
#EXTINF:-0,BBC Arabic News
http://livecdnh2.tvanywhere.ae/hls/bbc_ar/04.m3u8
#EXTINF:-0,Russia Today
https://rt-arab-gd.secure2.footprint.net/1104_800Kb.m3u8
#EXTINF:-0,ps
http://htvpalsat.mada.ps:8888/PBC/tracks-v1a1/mono.m3u8
#EXTINF:-0,Alsharq
http://mn-nl.mncdn.com/elsharq_live/live/chunklist.m3u8
#EXTINF:-0,watantv
http://watantv.origin.technostreaming.net:8081/watantv_source2/live/chunks.m3u8
#EXTINF:-0,hadath
https://av.alarabiya.net/alarabiapublish/alhadath.smil/playlist_720p.m3u8
#EXTINF:-0,Al Arabiya 
http://livecdnh3.tvanywhere.ae/hls/alarabiya/04.m3u8
#EXTINF:-0,Al Arabiya (1080)
https://av.alarabiya.net/alarabiapublish/alarabiya_720p/chunks.m3u8
#EXTINF:-0,Aljazeera Mubasher
https://live-hls-web-ajm.getaj.net/AJM/01.m3u8
#EXTINF:-0,alalam
https://live2.alalamtv.net/live/Alalam/index.m3u8
#EXTINF:-0,skynewsarabia HD 
http://livecdnh3.tvanywhere.ae/hls/skynewsar/04.m3u8
#EXTINF:-0,skynewsarabia HD +
https://stream.skynewsarabia.com/hls/sna_720.m3u8
#EXTINF:-1,FR 24 news 
http://f24hls-i.akamaihd.net/hls/live/221148/F24_AR_HI_HLS/master_900.m3u8
#EXTINF:-0, ||||||| Documentary|||||||
http://cdnworld.magictvbox.eu/Nat_Geo_Wild/tracks-v1a1/index.m3u8?token=b04f6e1d3917019e1ca2559684a5aad5673f376e
#EXTINF:-0,Al Jazeera Documentary
https://edge-1192-ch-gv.filmon.com/live/3029.high.stream/playlist.m3u8
#EXTINF:-1,Nat Geo HD ar
http://livecdnh2.tvanywhere.ae/hls/nat_geo_auh/index.m3u8
#EXTINF:-1,nat geo eng
http://livecdnh1.tvanywhere.ae:80/hls/nat_geo/05.m3u8
#EXTINF:-0, ||||||| isrl amos|||||||
http://besttv199.aoslive.it.best-tv.com/reshet/studio/index_1.m3u8
#EXTINF:-0,ch 13
https://reshet-live-il.ctedgecdn.net/13tv-desktop/r13_1200.m3u8
#EXTINF:-0,ch 12
https://keshethlslive-lh.akamaihd.net/i/CH12CC_1@732426/index_2200.m3u8 
#EXTINF:-0,ch 12(news)
http://keshethlslive-lh.akamaihd.net/i/c2n_1@195269/index_2200_av-p.m3u8 
#EXTINF:-0 ,Channel 20
https://dvr.ch20-cdnwiz.com/mobilehls/dvr_high/index.m3u8
#EXTINF:-1,ch 11
https://kanlivep2event-i.akamaihd.net/hls/live/747610/747610/source1_350/chunklist.m3u8
#EXTINF:-1,ch 11 1080 
https://kanlivep2event-i.akamaihd.net/hls/live/747610/747610/source1_2.5k/chunklist.m3u8
#EXTINF:-0,ch 23 HENICKETA
https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/source1_1.8k/chunklist.m3u8
#EXTINF:-0,ch 33 
https://kanlivep2event-i.akamaihd.net/hls/live/747613-b/747613/source1_1.2k/chunklist.m3u8
#EXTINF:-0,ch 33 1080 
https://kanlivep2event-i.akamaihd.net/hls/live/747613-b/747613/source1_2.5k/chunklist.m3u8
#EXTINF:-0,hala-tv
https://gstream4.panet.co.il/edge/halaTV/chunks.m3u8?
#EXTINF:-0 ,Knesset 
http://w3.013.gostreaming.tv:1935/Knesset/myStream/playlist.m3u8
#EXTINF:-0,Shopping
http://82.80.192.11/shoppingil_ShoppingIL21TVRepeat/_definst_/smil:ShoppingIL21TV.smil/playlist.m3u8
#EXTINF:-0,ch 24
https://keshethlslive-lh.akamaihd.net/i/24live_1@195271/index_2200_av-b.m3u8?sd=10&rebase=on
#EXTINF:-0 ,Channel 66
http://edge1.il.kab.tv/rtplive/tv66-heb-medium.stream/chunklist.m3u8
#EXTINF:-0 ,YNET LIVE 
https://ynet-lh.akamaihd.net/i/ynet_1@123290/index_3_av-p.m3u8?sd=10&rebase=on
#EXTINF:-0 ,SPORT 5 RADIO 
https://sport5-lh.akamaihd.net/i/radiolivev_0@698733/index_1_av-p.m3u8
#EXTINF:-0 ,Yeshua Chai TV
https://ihoplive-f.akamaihd.net/i/yeshuachai_tv@124973/index_2_av-p.m3u8?sd=10&rebase=on
#EXTINF:-0, ||||||| MBC |||||||
http://www.elahmad.com/tv/m3u8/ktv.m3u8?id=ktsv6
#EXTINF:-1,Mbc1 
http://188.160.0.148:1935/59afc8adc301977/_definst_/smil:myStream.smil/playlist.m3u8
#EXTINF:-1,Mbc1+
http://livecdnh2.tvanywhere.ae/hls/mbc1/03.m3u8
#EXTINF:-1 ,Mbc2
http://188.160.0.148:1935/599d303b80a2291/_definst_/smil:myStream.smil/playlist.m3u8
#EXTINF:-1,Mbc2 +
http://livecdnh3.tvanywhere.ae/hls/mbc2/index.m3u8
#EXTINF:-1,Mbc3 
http://livecdnh2.tvanywhere.ae/hls/mbc3/index.m3u8
#EXTINF:-1,MBC4 
http://livecdnh3.tvanywhere.ae/hls/mbc4/index.m3u8
#EXTINF:-1,mbc action 
http://livecdnh3.tvanywhere.ae/hls/mbcaction/index.m3u8
#EXTINF:-1,MBC-MAX 
http://livecdnh3.tvanywhere.ae/hls/mbcmax/index.m3u8
#EXTINF:-1,mbc DRAMA 
http://livecdnh2.tvanywhere.ae/hls/mbc_drama/index.m3u8
#EXTINF:-1,MBC-Bollywood 
http://livecdnh2.tvanywhere.ae/hls/mbc_bolly/index.m3u8
#EXTINF:-0,mbc msr 
http://livecdnh2.tvanywhere.ae/hls/mbc_msr/index.m3u8
#EXTINF:-1,Hawacom
http://livecdnh3.tvanywhere.ae/hls/hawacom/index.m3u8
#EXTINF:-0,wanasah 
http://livecdnh2.tvanywhere.ae/hls/wanasah/04.m3u8
#EXTINF:-0,hawas 
http://livecdnh3.tvanywhere.ae/hls/hawas/index.m3u8
#EXTINF:-0, ||||||| Entertainment ||||||| 
http://roz3.mine.nu:8000/live/mtk18/uDl8OogaxR/2269.m3u
#EXTINF:-1,star movies
http://livecdnh1.tvanywhere.ae/hls/star_movies/index.m3u8
#EXTINF:-1,star world
http://livecdnh1.tvanywhere.ae/hls/star_world/index.m3u8
#EXTINF:-1,cin1
http://livecdnh1.tvanywhere.ae/hls/cin1/index.m3u8
#EXTINF:-1,music_now
http://livecdnh1.tvanywhere.ae/hls/music_now/04.m3u8
#EXTINF:-0, ||||||| syria lebanon|||||||
http://www.elahmad.com/tv/m3u8/ktv.m3u8?id=ktsv7
#EXTINF:-0,Future TV
http://livecdnh2.tvanywhere.ae/hls/future/04.m3u8
#EXTINF:-0,syria  TV
https://svs.itworkscdn.net/syriatvlive/syriatv.smil/syriatvpublish/syriatv_480p/chunks.m3u8
#EXTINF:-0,syria AL EKHBARIYA
http://www.elahmad.com/tv/m3u8/syriatv.m3u8?id=syria_news
#EXTINF:-0,sama tv  
https://svs.itworkscdn.net/samatvlive/sama.smil/samatv_720p_chunks.m3u8
#EXTINF:0,ANN
http://ns8.indexforce.com:1935/ann/ann/playlist.m3u8
#EXTINF:0,Syria tv nilsat
http://82.137.248.16:1935/Sat/stream31122019/playlist.m3u8
#EXTINF:-1 ,Mtv lebanon
http://188.160.0.148:1935/5c57ec4475d8538/_definst_/smil:myStream.smil/playlist.m3u8
#EXTINF:0, M T V +
http://livecdnh3.tvanywhere.ae/hls/MTVLbnHD/01.m3u8
#EXTINF:-0,SYRIA DREAME
http://livecdnh2.tvanywhere.ae/hls/syria_drama/index.m3u8
#EXTINF:0,  OTV Lebanon
https://svs.itworkscdn.net/otvlebanonlive/otv.smil/playlist_406p.m3u8
#EXTINF:-0,Lana tv
https://svs.itworkscdn.net/lanatvlive/lana/playlist.m3u8
#EXTINF:-1,LBC HD
https://rotana.hibridmedia.com/rotana/lbc_dabr/rotana/lbc_1080p/chunks.m3u8
#EXTINF:-1,NBN TV
http://livecdnh1.tvanywhere.ae/hls/nbn/index.m3u8
#EXTINF:-1,jadeed TV 
http://livecdnh3.tvanywhere.ae/hls/jadeed/01.m3u8
#EXTINF:-1,LebanonTV 
http://cdn.catiacast.video/tl/cad9e8dcbf3eca0f7c2af160b1913cf4.sdp/chunks.m3u8
#EXTINF:-0,||||||| Gulf|||||||
http://mbcwanasatv-live.hls.adaptive.level3.net/hls-live/mbc-wanasatv/_definst_/live/stream1.m3u8
#EXTINF:0,DUBAI one
http://www.elahmad.com/tv/m3u8/dubaitv.m3u8?id=dubaione
#EXTINF:0,DUBAI TV
http://dmisxthvll.cdn.mangomolo.com/dubaitv/smil:dubaitv.stream.smil/playlist.m3u8
#EXTINF:0,Dubai Noor Dubai TV
http://dmiffthvll.cdn.mangomolo.com/noordubaitv/smil:noordubaitv.smil/chunklist.m3u8
#EXTINF:-0,dubaizaman 
http://dmiffthvll.cdn.mangomolo.com/dubaizaman/smil:dubaizaman.stream.smil/chunklist_b120000.m3u8
#EXTINF:0,Dubai sama 
http://dmieigthvll.cdn.mangomolo.com/samadubai/smil:samadubai.stream.smil/chunklist.m3u8
#EXTINF:-0,Abu Dhabi TV 
http://www.elahmad.com/tv/m3u8/adtv.m3u8?id=abudhabi_aloula
#EXTINF:-0,adaloula
http://admdn2.cdn.mangomolo.com/adtv/smil:adtv.stream.smil/chunklist.m3u8
#EXTINF:-0,Abu Dhabi Drama 
http://admdn5.cdn.mangomolo.com/drama/smil:drama.stream.smil/chunklist.m3u8
#EXTINF:-0,Emarat TV 
http://admdn3.cdn.mangomolo.com/emarat/smil:emarat.stream.smil/chunklist.m3u8
#EXTINF:-1,Sharjah TV
https://svs.itworkscdn.net/smc1live/smc1.smil/playlist_1080p.m3u8
#EXTINF:-0,SharjahTV kalbla
https://svs.itworkscdn.net/kablatvlive/kabtv1.smil/playlist_1080p.m3u8
#EXTINF:-0,ajman
http://livecdnh2.tvanywhere.ae/hls/ajman/04.m3u8
#EXTINF:-0,Al Rai
http://stream02.fasttelco.net/4/pub/asset/28/streams.m3u8?v=1053886998
#EXTINF:-0,Alaan.tv
http://livecdnh3.tvanywhere.ae/hls/alaantv/04.m3u8
#EXTINF:-0,alrayyan 1
https://svs.itworkscdn.net/alrayyanlive/alrayyan.smil/playlist_1080p.m3u8
#EXTINF:-0,alrayyan 2
https://svs.itworkscdn.net/alrayyanqadeemlive/alrayyanqadeem.smil/playlist_1080p.m3u8
#EXTINF:-0,KUWAIT",KTV 1
https://kwmedia.hibridmedia.com/kwmedia/kwtv1_dabr/kwmedia/kwtv1_360p/chunks.m3u8
#EXTINF:-0,KUWAIT",KTV 2
https://kwmedia.hibridmedia.com/kwmedia/kwtv2_dabr/kwmedia/kwtv2_1080p/chunks.m3u8
#EXTINF:-0,KUWAIT",KTV Ethraa
https://kwmedia.hibridmedia.com/kwmedia/kwtvethraa_dabr/kwmedia/kwtvethraa_1080p/chunks.m3u8
#EXTINF:-0,KTV Al Arabi
https://kwmedia.hibridmedia.com/kwmedia/kwtvarabi_dabr/kwmedia/kwtvarabi_1080p/chunks.m3u8
#EXTINF:-0,KTV Plus
https://kwmedia.hibridmedia.com/kwmedia/kwtvsportsplus_dabr/kwmedia/kwtvsportsplus_1080p/chunks.m3u8
#EXTINF:-0,KTV Al Majlis
https://kwmedia.hibridmedia.com/kwmedia/kwtvmajlis_dabr/kwmedia/kwtvmajlis_1080p/chunks.m3u8
#EXTINF:-0,qatartv
http://qatartv.akamaized.net/hls/live/691843/NewLive/index8.m3u8
#EXTINF:-1,FUNON tv
http://livecdnh3.tvanywhere.ae/hls/funoon/index.m3u8
#EXTINF:-1,Bahrain TV
http://185.105.4.106:1935/live/Bahrain%20TV/chunklist.m3u8
#EXTINF:-0,||||||| egybt|||||||
http://selevision9884-i.akamaihd.net/hls/live/219262/98846/1.m3u8?v=1460538461
#EXTINF:-0,zeeaflaam hd 
http://livecdnh3.tvanywhere.ae/hls/zeeaflam/index.m3u8
#EXTINF:-1,B4u Aflam
http://livecdnh3.tvanywhere.ae/hls/b4uaflam/04.m3u8
#EXTINF:-1,nahar drama
http://livecdnh2.tvanywhere.ae/hls/nahar_sd_drama/index.m3u8
#EXTINF:-1,nile drama
http://livecdnh2.tvanywhere.ae/hls/nile_drama/index.m3u8
#EXTINF:-1,nahar TV
http://livecdnh2.tvanywhere.ae/hls/nahar_sd/index.m3u8
#EXTINF:-1,hayat 1 TV
http://livecdnh2.tvanywhere.ae/hls/hayat/index.m3u8
#EXTINF:0, DMC
http://livecdnh3.tvanywhere.ae/hls/dmchd/04.m3u8
#EXTINF:0, dmcdrama
http://livecdnh1.tvanywhere.ae/hls/dmcdrama/04.m3u8
#EXTINF:-1,ROTANA CINEMA 
https://rotana.hibridmedia.com/rotana/cinema_dabr/rotana/cinema_1080p/chunks.m3u8
#EXTINF:-1,ROTANA comedy
https://rotana.hibridmedia.com/rotana/comedy_dabr/rotana/comedy_1080p/chunks.m3u8
#EXTINF:-1,Rotana Classic
https://rotana.hibridmedia.com/rotana/classical_dabr/rotana/classical_1080p/chunks.m3u8
#EXTINF:-1,ROTANA drama 
https://rotana.hibridmedia.com/rotana/drama_dabr/rotana/drama_1080p/chunks.m3u8
#EXTINF:-1,ROTANA KHALIJI 
https://rotana.hibridmedia.com/rotana/khaleejiya_dabr/rotana/khaleejiya_1080p/chunks.m3u8
#EXTINF:-1,rotclip
http://livecdnh3.tvanywhere.ae/hls/rotclip/index.m3u8
#EXTINF:-1,Nile drama 
http://livecdnh2.tvanywhere.ae/hls/nile_drama/04.m3u8
#EXTINF:-1,Nile SPORT 
http://livecdnh2.tvanywhere.ae/hls/nile_sp/04.m3u8
#EXTINF:-1,Sada balad
http://livecdnh1.tvanywhere.ae/hls/sada_balad/04.m3u8
#EXTINF:-1,kahera nas
http://livecdnh2.tvanywhere.ae/hls/kahera_nas/04.m3u8
#EXTINF:-0,RotanaEGY 
http://95.170.215.109/hls/RotanaEGY-Backup-M.m3u8
#EXTINF:-0,DREAM TV 
http://livecdnh2.tvanywhere.ae/hls/dream2/04.m3u8
#EXTINF:-0,||||||| SPORT |||||||
http://htvmada.mada.ps:8888/salamtv/playlist.mj3u8
#EXTINF:-0,AD Sport 1 HD
https://admdn1.cdn.mangomolo.com/adsports1/smil:adsports1.stream.smil/chunklist.m3u8
#EXTINF:-0,AD Sport 2 HD
https://admdn5.cdn.mangomolo.com/adsports2/smil:adsports2.stream.smil/chunklist.m3u8
#EXTINF:-0,AD Sport 3 HD
https://admdn3.cdn.mangomolo.com/adsports3/smil:adsports3.stream.smil/chunklist.m3u8
#EXTINF:-0,AD Sport 4 HD
https://admdn4.cdn.mangomolo.com/adsports4/smil:adsports4.stream.smil/chunklist.m3u8
#EXTINF:-0,DUBAI SPORTS 
http://dmitnthvll.cdn.mangomolo.com/dubaisports/smil:dubaisports.smil/chunklist.m3u8
#EXTINF:-0,DUBAI RACING
http://dmithrvll.cdn.mangomolo.com/dubairacing/smil:dubairacing.smil/chunklist.m3u8
#EXTINF:-0,Sharjah sport
https://svs.itworkscdn.net/smc4sportslive/smc4.smil/chunklist.m3u8
#EXTINF:-1,KSA Sports HQ
https://ch.iptvmate.net/78c2e8d653a0c3020a0efd0afc66f903.m3u8
#EXTINF:-0,|||||| PS |||||||
http://htv.mada.ps:8888/ftv/ftv/tracks-v1a11/index.m3u8
#EXTINF:-0,najah
http://htvpalsat.mada.ps:8888/najah/tracks-v1a1/mono.m3u8
#EXTINF:-0,PBCLive
http://htvpalsat.mada.ps:8888/PBCLive/tracks-v1a1/mono.m3u8
#EXTINF:-0,paltv today
http://live.paltoday.tv:1935/paltv/live/chunklist.m3u8
#EXTINF:-0,Awdeh TV
http://htvpalsat.mada.ps:8888/audeh/tracks-v1a1/mono.m3u8
#EXTINF:-0,aqsatv TV
https://live-1.linuxway.info/aqsatv/live/tv/chunklist.m3u8
#EXTINF:0, Watar hd
http://htvint.mada.ps:8889/orient/tracks-v1a1/mono.m3u8
#EXTINF:-0,Musawa
http://htvpalsat.mada.ps:8888/musawa/tracks-v1a1/mono.m3u8
#EXTINF:-1,MaanHD
http://htvmada.mada.ps:8888/maannews/tracks-v1a1/mono.m3u8
#EXTINF:-1,palestiniantv
http://palestiniantv.origin.technostreaming.net:8081/palestiniantv_source/live/chunks.m3u8
#EXTINF:-1,MawwalHD
http://vstream3.hadara.ps:8081/MawwalHD_web/web/chunks.m3u8
#EXTINF:-1,Almahed
http://vstream3.hadara.ps:8081/Almahed/Almahed/playlist.m3u8
#EXTINF:-0,honaalquds
http://82.212.74.99:8000/live/hls/8170.m3u8
#EXTINF:-0,||||||| arab tv |||||||
http://htv.mada.ps:8888/ftv/ftv/tracks-v1a1/index.m3u8
#EXTINF:-0,DW Arabia
https://dwstream2-lh.akamaihd.net/i/dwstream2_live@124400/index_1_av-p.m3u8
#EXTINF:-0 , TRT Arabic
https://tv-trtarabi.live.trt.com.tr/master_1080.m3u8
#EXTINF:0, Roya tv
https://roya-live.ercdn.net/roya/roya_720p.m3u8
#EXTINF:0, almamlka
https://almamlka-live.ercdn.net/almamlka/almamlka_1080p.m3u8
#EXTINF:-0,Jordantv
http://livecdnh2.tvanywhere.ae/hls/jordan/04.m3u8
#EXTINF:-0,Amman TV
https://ammantv.c.s73cdn.net/23153d43-375a-472a-bc5f-9827582b5d22/elemental/live/master.m3u8
#EXTINF:-0,Jordantv sport
http://stream.joinvisions.net:1935/jorlive/sport/chunklist.m3u8
#EXTINF:0, Hura 
http://mbnhls-lh.akamaihd.net/i/MBN_1@118619/master.m3u8
#EXTINF:-1,arrafidaintv
http://149.202.79.190:8081/arrafidaintv/publish/chunks.m3u8
#EXTINF:-1,Hadath 
http://streamer12.elementssys.com:8080/demo/Hadath/index.m3u8
#EXTINF:-1,alrashid
http://streamer11.elementssys.com:8080/alrashid/alrashid_650kbps/index.m3u8
#EXTINF:-1,Dijlah
http://91.134.145.75:10001/Dijlah/tracks-v1a1/mono.m3u8
#EXTINF:-1,alforat tv
http://212.18.231.213:1935/7/7_360p/chunklist.m3u8
#EXTINF:-1,Alsharqiya hd
http://ns8.indexforce.com:1935/alsharqiyalive/mystream/chunklist.m3u8
#EXTINF:-1,Al Taghayer
https://ch.iptvmate.net/badad6dd5d52c994176379dee9df409b.m3u8
#EXTINF:-0,||||||| Morocco|||||||
http://streaming.i-sat.tv:1935/live/semsem/chunklist_w1565880249.m3u8
#EXTINF:-0,2m
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/2m_monde-avc1_1500000=11-mp4a_130400_qad=1.m3u8
#EXTINF:-0,al_aoula
http://cdn-hls.globecast.tv/live/ramdisk/al_aoula_inter/hls_snrt/index.m3u8
#EXTINF:-0,arrabiaa
http://cdn-hls.globecast.tv/live/ramdisk/arrabiaa/hls_snrt/index.m3u8
#EXTINF:-0,al_maghribia
http://cdn-hls.globecast.tv/live/ramdisk/al_maghribia_snrt/hls_snrt/index.m3u8
#EXTINF:-0,assadissa
http://cdn-hls.globecast.tv/live/ramdisk/assadissa/hls_snrt/index.m3u8
#EXTINF:-0,Medi1tvmaghreb
https://streaming.medi1tv.com/live/Medi1tvmaghreb.sdp/chunklist.m3u8
#EXTINF:-1,nessma tv
http://livecdnh2.tvanywhere.ae/hls/nessma/index.m3u8
#EXTINF:-0,libyaschannel
http://starmena.ercdn.net/libyaschannel/libyaschannel_480p.m3u8
#EXTINF:-0,libya alhadath
http://starmena.ercdn.net/libya-alhadath/libya-alhadath_480p.m3u8
#EXTINF:-0,tanasuhtv
http://m.live.net.sa:1935/m/tanasuhtv/chunklist.m3u8
#EXTINF:-0,libya futuer
http://streamer11.elementssys.com:8080/demo/rasmyah/index.m3u8
#EXTINF:-6,2018 TV
https://stream.218tv.net/libya218TV/tracks-v1a1/mono.m3u8
#EXTINF:-6,2018 news
https://stream.218tv.net/libya218news/tracks-v1a1/mono.m3u8
#EXTINF:-0, ||||||| Christians|||||||
http://htv.mada.ps:8888/ftv/f1tv/tracks-v1a1/index.m3u8222
#EXTINF:-1,sat 7
http://unirtmp.tulix.tv:1935/sat7arabic/satarabiclive-web.smil/chunklist.m3u8
#EXTINF:-1,sat7 kids
http://unirtmp.tulix.tv:1935/sat7kids/satkidslive-web.smil/chunklist.m3u8
#EXTINF:-1,logos tv
http://66.165.251.10:1935/logoschannel.com/logostv.smil/chunklist.m3u8
#EXTINF:-1,ABNNSAT
http://rtmp1.abnsat.com/hls/arabic.m3u8
#EXTINF:-1,Alkerazatv
http://media4.smc-host.com:1935/alkerazatv.org/alkerazatv.smil/chunklist.m3u8
#EXTINF:-1,koogi
http://68.235.60.118:1935/koogi.tv/koogi.smil/playlist.m3u8
#EXTINF:-1,nour4sat
https://svs.itworkscdn.net/nour1satlive/livestream/chunks.m3u8
#EXTINF:-1,Radio-charity
http://cast5.servcast.net:9990/stream
